-- Bergama Doğa Lisesi kütüphane veritabanı
-- Supabase Dashboard > SQL Editor > New query bölümünde çalıştır.

create table if not exists public.books (
  id bigint generated by default as identity primary key,
  title text not null,
  author text not null,
  category text not null default 'Roman',
  shelf text not null default '',
  status text not null default 'Rafta' check (status in ('Rafta', 'Ödünçte')),
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.books drop column if exists year;

alter table public.books enable row level security;

-- İlk kurulum için giriş yapmadan listeleme ve kitap ekleme izni.
-- Gerçek kullanıma geçerken Supabase Auth ekleyip bu politikaları daraltın.
drop policy if exists "Herkes kitapları görebilir" on public.books;
create policy "Herkes kitapları görebilir"
  on public.books for select
  to anon, authenticated
  using (true);

drop policy if exists "Herkes kitap ekleyebilir" on public.books;
create policy "Herkes kitap ekleyebilir"
  on public.books for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Herkes kitap durumunu güncelleyebilir" on public.books;
create policy "Herkes kitap durumunu güncelleyebilir"
  on public.books for update
  to anon, authenticated
  using (true)
  with check (true);

drop policy if exists "Herkes kitap silebilir" on public.books;
create policy "Herkes kitap silebilir"
  on public.books for delete
  to anon, authenticated
  using (true);

create table if not exists public.loans (
  id bigint generated by default as identity primary key,
  book_id bigint not null references public.books(id) on delete cascade,
  borrower_name text not null,
  borrower_number text not null default '',
  borrowed_at timestamptz not null default timezone('utc', now()),
  due_at date,
  returned_at timestamptz,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.loans add column if not exists borrower_number text not null default '';

alter table public.loans enable row level security;

drop policy if exists "Herkes ödünç kayıtlarını görebilir" on public.loans;
create policy "Herkes ödünç kayıtlarını görebilir"
  on public.loans for select
  to anon, authenticated
  using (true);

drop policy if exists "Herkes ödünç kaydı ekleyebilir" on public.loans;
create policy "Herkes ödünç kaydı ekleyebilir"
  on public.loans for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Herkes ödünç kaydını güncelleyebilir" on public.loans;
create policy "Herkes ödünç kaydını güncelleyebilir"
  on public.loans for update
  to anon, authenticated
  using (true)
  with check (true);

